services:
  - type: web
    name: interlink-backend
    env: node
    plan: free
    buildCommand: cp package.deploy.json package.json && npm install --production
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: noreply@interlink.com
      - key: FROM_NAME
        value: InterLink
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: FACEBOOK_APP_ID
        sync: false
      - key: FACEBOOK_APP_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://interlinkweb.netlify.app
      - key: CORS_ORIGIN
        value: https://interlinkweb.netlify.app
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_FILE_TYPES
        value: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx,ppt,pptx
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: LOG_FILE
        value: logs/app.log
      - key: RENDER_EXTERNAL_URL
        value: https://interlink-1lil.onrender.com